### ISSUE TITLE
[enhancement] Add missing bower.json.

### ISSUE THREAD

**Issue by timgluz** [alanhogan/Tabby#10]
#### Hey, maintainer(s) of alanhogan/Tabby!

We at [VersionEye](https://www.versioneye.com/signup?promo_code=BOWER) are working hard to keep up the quality of the bower's registry.

We just finished our initial analysis of the quality of the Bower.io registry:

**7530** - registered packages, *224* of them doesnt exists anymore;

We analysed **7306**  existing packages and  **1070** of them don't have bower.json on the master branch ( _that's where a Bower client pulls a data_ ).

Sadly, your library `alanhogan/Tabby` is one of them.

Can you spare **15** minutes to help us to make Bower better?

Just add a new file `bower.json` and  change attributes.

```
{
  "name": "alanhogan/Tabby",
  "version": "1.0.0",
  "main": "path/to/main.css",
  "description": "please add it",
  "license": "Eclipse",
  "ignore": [
    ".jshintrc",
    "**/*.txt"
  ],
  "dependencies": {
    "<dependency_name>": "<semantic_version>",
    "<dependency_name>": "<Local_folder>",
    "<dependency_name>": "<package>"
  },
  "devDependencies": {
    "<test-framework-name>": "<version>"
  }
}

```

Read more about bower.json [on the official spefication](http://bower.io/#defining-a-package) and nodejs [semver](https://github.com/isaacs/node-semver#ranges) library has great examples of proper versioning.

**NB!** Please _validate_ your bower.json with _jsonlint_ before commiting your updates.

Thank you!

Timo,
twitter: @versioneye
email: timo@versioneye.com
[VersionEye](https://www.versioneye.com/signup?promo_code=BOWER) - no more legacy software!

**Comment by diversen** [comment]
This would be a nice feature.

**Comment by alanhogan** [comment]
I sat on this for a long time because it wasn’t originally my code and I wasn’t sure what to put in for the license, but it seems Ted originally chose the liberal FOSS license BSD (3-clause).  http://web.archive.org/web/20110716201529/http://teddevito.com/demos/js/jquery.textarea.js

**Comment by alanhogan** [comment]
@diversen npm seems to be winning out in general. okay if I add a package.json but no bower file? Have any thoughts on that one way or the other?

**Comment by alanhogan** [comment]
I’ve finally gone and added a `package.json` file. Hopefully that satisfies this issue. Let me know if there is good reason to add a `bower.json` as well, and I’ll happily do it. For now, I’ll close this issue.
