### ISSUE TITLE
Closure scope not respected with setTimeout call

### ISSUE THREAD

**Issue by chriscdn** [alanhogan/Tabby#7]
On lines 52, 53, & 57 a setTimeout is used with the function argument passed in as a string.  This gets executed with $ being the global value and not the $ in the closure scope.  A fix is to change those lines to:

52: if (17 == kc) {pressed.ctrl = true; setTimeout(function(){$.fn.tabby.pressed.ctrl = false;},1000);}
53: if (18 == kc) {pressed.alt = true; setTimeout(function(){$.fn.tabby.pressed.alt = false;},1000);}
57: pressed.last = kc;	setTimeout(function(){$.fn.tabby.pressed.last = null;},0);

**Comment by alanhogan** [comment]
This was fixed via PR. https://github.com/alanhogan/Tabby/commit/925c5a416afc9233ba31e3fb7aff043a1a802ce6
